# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171102_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=256, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
    ]
