# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171102_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='介绍'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(default='', max_length=256, verbose_name='关键词'),
        ),
    ]
